{
 "title": "Play times",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rocks per total play",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rock_count / play_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Paper per total play",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "paper_count / play_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Play Times",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "play_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scissors per total play",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scissors_count / play_count", "legendFormat": "__auto" }
   ]
  }
 ]
}